[package]
name = "peerline-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
blake3.workspace = true
futures.workspace = true
hmac.workspace = true
if-addrs.workspace = true
igd-next.workspace = true
libp2p.workspace = true
libp2p-webrtc.workspace = true
local-ip-address.workspace = true
rand.workspace = true
peerline-core = { path = "../peerline-core" }
peerline-crypto = { path = "../peerline-crypto" }
peerline-rendezvous-model = { path = "../peerline-rendezvous-model" }
peerline-transfer = { path = "../peerline-transfer" }
postcard.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true
