[package]
name = "peerline-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "peerline"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
rand.workspace = true
peerline-core = { path = "../peerline-core" }
peerline-net = { path = "../peerline-net" }
peerline-tui = { path = "../peerline-tui" }
peerline-transfer = { path = "../peerline-transfer" }
libp2p.workspace = true
rpassword.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
tempfile.workspace = true
